import type { CarListing } from '../types/search'

const img = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=800&q=80`

function generateFleet(base: CarListing[], count: number): CarListing[] {
  const fleet: CarListing[] = []
  for (let i = 0; i < count; i++) {
    const template = base[i % base.length]
    fleet.push({
      ...template,
      category: template.category ?? 'regular',
      year: template.year ?? 2020 + (i % 6),
      id: String(i + 1),
      name: i < base.length ? template.name : `${template.name} #${i + 1}`,
      reviews: template.reviews + (i % 50),
      pricePerDay: template.pricePerDay + (i % 5) * 100,
      popularity: Math.max(60, template.popularity - (i % 20)),
    })
  }
  return fleet
}

const MOCK_CARS_BASE: CarListing[] = [
  {
    id: '1',
    brand: 'Mahindra',
    model: 'XUV700 AX7',
    name: 'Mahindra XUV700 AX7',
    vehicleType: 'suv',
    category: 'regular',
    transmission: 'automatic',
    fuel: 'diesel',
    seats: 7,
    mileage: '15 km/l',
    rating: 4.8,
    reviews: 210,
    pricePerDay: 3999,
    originalPrice: 5200,
    securityDeposit: 5000,
    images: [
      img('photo-1549317661-bd32c8ce0db2'),
      img('photo-1519641471654-76ce0107a1bf'),
      img('photo-1533473359601-0a1756b8a1b7'),
    ],
    featureChips: [
      'Unlimited KM',
      'FastTag Included',
      'Music System',
      'USB Charging',
      'Reverse Camera',
      'ABS',
      'Airbags',
      'Fuel Efficient',
    ],
    amenities: { ac: true, bluetooth: true, gps: true },
    badges: ['available', 'discount', 'popular'],
    discountPercent: 10,
    tag: 'Best for Family',
    cancellationPolicy: 'Free cancellation up to 24 hrs',
    unlimitedKm: true,
    instantBooking: true,
    freeCancellation: true,
    airConditioning: true,
    bluetoothFeature: true,
    sunroof: true,
    popularity: 98,
    createdAt: '2026-01-15',
  },
  {
    id: '2',
    brand: 'Hyundai',
    model: 'Creta SX(O)',
    name: 'Hyundai Creta SX(O)',
    vehicleType: 'suv',
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 5,
    mileage: '17 km/l',
    rating: 4.7,
    reviews: 342,
    pricePerDay: 2899,
    originalPrice: 3500,
    securityDeposit: 4000,
    images: [
      img('photo-1606664515524-ed2f786a0bd6'),
      img('photo-1552519507-da3b142c6e3d'),
    ],
    featureChips: [
      'Unlimited KM',
      'FastTag Included',
      'Sunroof',
      'Reverse Camera',
      'ABS',
      'Airbags',
    ],
    amenities: { ac: true, bluetooth: true, gps: true },
    badges: ['available', 'popular'],
    tag: 'Great Mileage',
    cancellationPolicy: 'Free cancellation up to 12 hrs',
    unlimitedKm: true,
    instantBooking: true,
    freeCancellation: true,
    airConditioning: true,
    bluetoothFeature: true,
    sunroof: true,
    popularity: 95,
    createdAt: '2026-02-01',
  },
  {
    id: '3',
    brand: 'Toyota',
    model: 'Innova Crysta',
    name: 'Toyota Innova Crysta',
    vehicleType: 'muv',
    transmission: 'automatic',
    fuel: 'diesel',
    seats: 7,
    mileage: '14 km/l',
    rating: 4.9,
    reviews: 456,
    pricePerDay: 4499,
    originalPrice: 5500,
    securityDeposit: 6000,
    images: [img('photo-1583121274602-3e2820c50a8a')],
    featureChips: [
      'Unlimited KM',
      'FastTag Included',
      'Music System',
      'USB Charging',
      'Reverse Camera',
      'ABS',
      'Airbags',
    ],
    amenities: { ac: true, bluetooth: true, gps: true },
    badges: ['available', 'discount'],
    discountPercent: 8,
    tag: 'Best for Groups',
    cancellationPolicy: 'Free cancellation up to 24 hrs',
    unlimitedKm: true,
    instantBooking: false,
    freeCancellation: true,
    airConditioning: true,
    bluetoothFeature: true,
    sunroof: false,
    popularity: 92,
    createdAt: '2025-11-20',
  },
  {
    id: '4',
    brand: 'Honda',
    model: 'City ZX CVT',
    name: 'Honda City ZX CVT',
    vehicleType: 'sedan',
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 5,
    mileage: '18 km/l',
    rating: 4.6,
    reviews: 189,
    pricePerDay: 2499,
    originalPrice: 2999,
    securityDeposit: 3500,
    images: [img('photo-1621007947382-bb3b3c4f4b3d')],
    featureChips: ['FastTag Included', 'Music System', 'USB Charging', 'ABS', 'Airbags'],
    amenities: { ac: true, bluetooth: true, gps: false },
    badges: ['available'],
    tag: 'Fuel Efficient',
    cancellationPolicy: 'Free cancellation up to 6 hrs',
    unlimitedKm: false,
    instantBooking: true,
    freeCancellation: false,
    airConditioning: true,
    bluetoothFeature: true,
    sunroof: false,
    popularity: 88,
    createdAt: '2026-03-10',
  },
  {
    id: '5',
    brand: 'BMW',
    model: 'X5 xDrive40i',
    name: 'BMW X5 xDrive40i',
    vehicleType: 'luxury',
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 5,
    mileage: '11 km/l',
    rating: 4.9,
    reviews: 87,
    pricePerDay: 12999,
    originalPrice: 15000,
    securityDeposit: 25000,
    images: [img('photo-1555217692-1d1ee29d5b1a')],
    featureChips: [
      'Unlimited KM',
      'FastTag Included',
      'Sunroof',
      'Reverse Camera',
      'ABS',
      'Airbags',
      'Premium Audio',
    ],
    amenities: { ac: true, bluetooth: true, gps: true },
    badges: ['available', 'discount', 'popular'],
    discountPercent: 15,
    tag: 'Luxury Pick',
    cancellationPolicy: 'Free cancellation up to 48 hrs',
    unlimitedKm: true,
    instantBooking: true,
    freeCancellation: true,
    airConditioning: true,
    bluetoothFeature: true,
    sunroof: true,
    popularity: 90,
    createdAt: '2026-01-05',
  },
  {
    id: '6',
    brand: 'Tata',
    model: 'Nexon EV Max',
    name: 'Tata Nexon EV Max',
    vehicleType: 'electric',
    transmission: 'automatic',
    fuel: 'electric',
    seats: 5,
    mileage: '437 km range',
    rating: 4.5,
    reviews: 156,
    pricePerDay: 3199,
    originalPrice: 3800,
    securityDeposit: 5000,
    images: [img('photo-1593941707882-a5bba14938c7')],
    featureChips: [
      'Unlimited KM',
      'FastTag Included',
      'USB Charging',
      'Reverse Camera',
      'ABS',
      'Airbags',
      'Eco Mode',
    ],
    amenities: { ac: true, bluetooth: true, gps: true },
    badges: ['available'],
    tag: 'Eco Friendly',
    cancellationPolicy: 'Free cancellation up to 12 hrs',
    unlimitedKm: true,
    instantBooking: true,
    freeCancellation: true,
    airConditioning: true,
    bluetoothFeature: true,
    sunroof: false,
    popularity: 85,
    createdAt: '2026-02-20',
  },
  {
    id: '7',
    brand: 'Maruti',
    model: 'Swift VXI',
    name: 'Maruti Swift VXI',
    vehicleType: 'hatchback',
    transmission: 'manual',
    fuel: 'petrol',
    seats: 5,
    mileage: '22 km/l',
    rating: 4.4,
    reviews: 523,
    pricePerDay: 1499,
    originalPrice: 1800,
    securityDeposit: 2500,
    images: [img('photo-1541899481282-d53bffe3c35d')],
    featureChips: ['FastTag Included', 'Music System', 'ABS', 'Airbags', 'Fuel Efficient'],
    amenities: { ac: true, bluetooth: false, gps: false },
    badges: ['available', 'popular'],
    tag: 'Budget Friendly',
    cancellationPolicy: 'Non-refundable',
    unlimitedKm: false,
    instantBooking: true,
    freeCancellation: false,
    airConditioning: true,
    bluetoothFeature: false,
    sunroof: false,
    popularity: 96,
    createdAt: '2025-10-01',
  },
  {
    id: '8',
    brand: 'Jeep',
    model: 'Compass Limited',
    name: 'Jeep Compass Limited',
    vehicleType: 'suv',
    transmission: 'automatic',
    fuel: 'diesel',
    seats: 5,
    mileage: '16 km/l',
    rating: 4.7,
    reviews: 134,
    pricePerDay: 3799,
    originalPrice: 4500,
    securityDeposit: 5000,
    images: [img('photo-1519641471654-76ce0107a1bf')],
    featureChips: [
      'Unlimited KM',
      'FastTag Included',
      'Sunroof',
      'Reverse Camera',
      'ABS',
      'Airbags',
    ],
    amenities: { ac: true, bluetooth: true, gps: true },
    badges: ['available', 'discount'],
    discountPercent: 12,
    tag: 'Adventure Ready',
    cancellationPolicy: 'Free cancellation up to 24 hrs',
    unlimitedKm: true,
    instantBooking: true,
    freeCancellation: true,
    airConditioning: true,
    bluetoothFeature: true,
    sunroof: true,
    popularity: 87,
    createdAt: '2026-01-28',
  },
  {
    id: '9',
    brand: 'Mercedes',
    model: 'E-Class E220d',
    name: 'Mercedes E-Class E220d',
    vehicleType: 'luxury',
    transmission: 'automatic',
    fuel: 'diesel',
    seats: 5,
    mileage: '15 km/l',
    rating: 5,
    reviews: 64,
    pricePerDay: 14999,
    originalPrice: 17000,
    securityDeposit: 30000,
    images: [img('photo-1618843479313-40f8afb4b4d8')],
    featureChips: [
      'Unlimited KM',
      'FastTag Included',
      'Premium Audio',
      'Sunroof',
      'Reverse Camera',
      'ABS',
      'Airbags',
    ],
    amenities: { ac: true, bluetooth: true, gps: true },
    badges: ['available', 'popular'],
    tag: 'Executive Class',
    cancellationPolicy: 'Free cancellation up to 48 hrs',
    unlimitedKm: true,
    instantBooking: false,
    freeCancellation: true,
    airConditioning: true,
    bluetoothFeature: true,
    sunroof: true,
    popularity: 82,
    createdAt: '2025-12-15',
  },
  {
    id: '10',
    brand: 'Kia',
    model: 'Seltos GTX+',
    name: 'Kia Seltos GTX+',
    vehicleType: 'suv',
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 5,
    mileage: '16 km/l',
    rating: 4.6,
    reviews: 278,
    pricePerDay: 2699,
    originalPrice: 3200,
    securityDeposit: 4000,
    images: [img('photo-1609521263047-f8f205293bb4')],
    featureChips: [
      'Unlimited KM',
      'FastTag Included',
      'Music System',
      'USB Charging',
      'Reverse Camera',
      'ABS',
      'Airbags',
    ],
    amenities: { ac: true, bluetooth: true, gps: true },
    badges: ['available'],
    tag: 'City Cruiser',
    cancellationPolicy: 'Free cancellation up to 12 hrs',
    unlimitedKm: true,
    instantBooking: true,
    freeCancellation: true,
    airConditioning: true,
    bluetoothFeature: true,
    sunroof: true,
    popularity: 91,
    createdAt: '2026-02-05',
  },
  {
    id: '11',
    brand: 'Audi',
    model: 'Q5 Premium Plus',
    name: 'Audi Q5 Premium Plus',
    vehicleType: 'luxury',
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 5,
    mileage: '12 km/l',
    rating: 4.8,
    reviews: 92,
    pricePerDay: 11999,
    originalPrice: 14000,
    securityDeposit: 22000,
    images: [img('photo-1606664515524-ed2f786a0bd6')],
    featureChips: [
      'Unlimited KM',
      'FastTag Included',
      'Premium Audio',
      'Sunroof',
      'Reverse Camera',
      'ABS',
      'Airbags',
    ],
    amenities: { ac: true, bluetooth: true, gps: true },
    badges: ['available', 'discount'],
    discountPercent: 10,
    tag: 'Premium SUV',
    cancellationPolicy: 'Free cancellation up to 48 hrs',
    unlimitedKm: true,
    instantBooking: true,
    freeCancellation: true,
    airConditioning: true,
    bluetoothFeature: true,
    sunroof: true,
    popularity: 84,
    createdAt: '2026-01-20',
  },
  {
    id: '12',
    brand: 'Toyota',
    model: 'Fortuner Legender',
    name: 'Toyota Fortuner Legender',
    vehicleType: 'suv',
    transmission: 'automatic',
    fuel: 'diesel',
    seats: 7,
    mileage: '13 km/l',
    rating: 4.8,
    reviews: 198,
    pricePerDay: 5499,
    originalPrice: 6500,
    securityDeposit: 8000,
    images: [img('photo-1533473359601-0a1756b8a1b7')],
    featureChips: [
      'Unlimited KM',
      'FastTag Included',
      'Sunroof',
      'Reverse Camera',
      'ABS',
      'Airbags',
      '4x4 Ready',
    ],
    amenities: { ac: true, bluetooth: true, gps: true },
    badges: ['available', 'popular'],
    tag: 'Off-Road King',
    cancellationPolicy: 'Free cancellation up to 24 hrs',
    unlimitedKm: true,
    instantBooking: true,
    freeCancellation: true,
    airConditioning: true,
    bluetoothFeature: true,
    sunroof: true,
    popularity: 94,
    createdAt: '2025-11-01',
  },
]

const TOURISM_CARS_BASE: CarListing[] = [
  {
    id: 't1',
    brand: 'Mahindra',
    model: 'Thar Roxx',
    name: 'Mahindra Thar Roxx — Tourism',
    vehicleType: 'suv',
    category: 'tourism',
    transmission: 'manual',
    fuel: 'diesel',
    seats: 4,
    mileage: '14 km/l',
    rating: 4.9,
    reviews: 156,
    pricePerDay: 4499,
    originalPrice: 5500,
    securityDeposit: 7000,
    images: [
      img('photo-1533473359601-0a1756b8a1b7'),
      img('photo-1519641471654-76ce0107a1bf'),
    ],
    featureChips: [
      'Tour Package Ready',
      'Unlimited KM',
      'Hill Drive Ready',
      'Reverse Camera',
      'ABS',
      'Airbags',
    ],
    amenities: { ac: true, bluetooth: true, gps: true },
    badges: ['available', 'popular'],
    tag: 'Tourism Special',
    cancellationPolicy: 'Free cancellation up to 48 hrs',
    unlimitedKm: true,
    instantBooking: true,
    freeCancellation: true,
    airConditioning: true,
    bluetoothFeature: true,
    sunroof: false,
    popularity: 96,
    createdAt: '2026-03-01',
  },
  {
    id: 't2',
    brand: 'Toyota',
    model: 'Innova Crysta',
    name: 'Toyota Innova Crysta — Tourism',
    vehicleType: 'muv',
    category: 'tourism',
    transmission: 'automatic',
    fuel: 'diesel',
    seats: 7,
    mileage: '14 km/l',
    rating: 4.8,
    reviews: 280,
    pricePerDay: 4999,
    originalPrice: 6000,
    securityDeposit: 8000,
    images: [img('photo-1549317661-bd32c8ce0db2')],
    featureChips: [
      'Tour Package Ready',
      'Unlimited KM',
      'Family Tours',
      'FastTag Included',
      'ABS',
      'Airbags',
    ],
    amenities: { ac: true, bluetooth: true, gps: true },
    badges: ['available', 'discount', 'popular'],
    discountPercent: 12,
    tag: 'Tourism Special',
    cancellationPolicy: 'Free cancellation up to 48 hrs',
    unlimitedKm: true,
    instantBooking: true,
    freeCancellation: true,
    airConditioning: true,
    bluetoothFeature: true,
    sunroof: false,
    popularity: 97,
    createdAt: '2026-02-15',
  },
  {
    id: 't3',
    brand: 'Force',
    model: 'Traveller',
    name: 'Force Traveller 12-Seater — Tourism',
    vehicleType: 'muv',
    category: 'tourism',
    transmission: 'manual',
    fuel: 'diesel',
    seats: 8,
    mileage: '11 km/l',
    rating: 4.5,
    reviews: 88,
    pricePerDay: 6999,
    originalPrice: 8500,
    securityDeposit: 10000,
    images: [img('photo-1519641471654-76ce0107a1bf')],
    featureChips: [
      'Group Tours',
      'Tour Package Ready',
      'Luggage Space',
      'FastTag Included',
      'ABS',
    ],
    amenities: { ac: true, bluetooth: true, gps: true },
    badges: ['available'],
    tag: 'Group Tourism',
    cancellationPolicy: 'Free cancellation up to 72 hrs',
    unlimitedKm: true,
    instantBooking: false,
    freeCancellation: true,
    airConditioning: true,
    bluetoothFeature: true,
    sunroof: false,
    popularity: 82,
    createdAt: '2026-01-10',
  },
  {
    id: 't4',
    brand: 'Maruti',
    model: 'Ertiga ZXI',
    name: 'Maruti Ertiga ZXI — Tourism',
    vehicleType: 'muv',
    category: 'tourism',
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 7,
    mileage: '18 km/l',
    rating: 4.6,
    reviews: 142,
    pricePerDay: 3299,
    originalPrice: 4000,
    securityDeposit: 5000,
    images: [img('photo-1552519507-da3b142c6e3d')],
    featureChips: [
      'Tour Package Ready',
      'Fuel Efficient',
      'FastTag Included',
      'ABS',
      'Airbags',
    ],
    amenities: { ac: true, bluetooth: true, gps: true },
    badges: ['available', 'discount'],
    discountPercent: 10,
    tag: 'Tourism Special',
    cancellationPolicy: 'Free cancellation up to 24 hrs',
    unlimitedKm: true,
    instantBooking: true,
    freeCancellation: true,
    airConditioning: true,
    bluetoothFeature: true,
    sunroof: false,
    popularity: 88,
    createdAt: '2026-03-05',
  },
]

const REGULAR_FLEET = generateFleet(
  MOCK_CARS_BASE.filter((c) => (c.category ?? 'regular') === 'regular'),
  170,
)

const TOURISM_FLEET = generateFleet(TOURISM_CARS_BASE, 24).map((car, i) => ({
  ...car,
  category: 'tourism' as const,
  id: `t${i + 1}`,
}))

export const MOCK_CARS: CarListing[] = [...REGULAR_FLEET, ...TOURISM_FLEET]
